export const ICONS: { [key: string]: string } = {
  allGreatKnights: '/assets/hollowKnight/icons/misc/AllGreatKnights.png',
  allMasks: '/assets/hollowKnight/icons/achievements/AllMask.png',
  allMasksAllVessels:
    '/assets/hollowKnight/icons/achievements/AllMaskAllVessels.png',
  allStags: '/assets/hollowKnight/icons/achievements/AllStagStations.png',
  allVessels: '/assets/hollowKnight/icons/achievements/AllVessels.png',
  charmNotch: '/assets/hollowKnight/icons/items/CharmNotch.png',
  charmNotchGrimm: '/assets/hollowKnight/icons/items/CharmNotchGrimm.png',
  cityGateOpen: '/assets/hollowKnight/icons/misc/Hegemol.png',
  cityKey: '/assets/hollowKnight/icons/items/CityKey.png',
  colosseumBronze:
    '/assets/hollowKnight/icons/achievements/ColosseumBronze.png',
  delicateFlower: '/assets/hollowKnight/icons/items/DelicateFlower.png',
  dungDefender: '/assets/hollowKnight/icons/boss/DungDefender.png',
  elegantKey: '/assets/hollowKnight/icons/items/ElegantKey.png',
  elegy: '/assets/hollowKnight/icons/charms/GrubberflysElegy.png',
  grimmchild: '/assets/hollowKnight/icons/charms/Grimmchild.png',
  grimmchild2: '/assets/hollowKnight/icons/charms/Grimmchild2.png',
  grub: '/assets/hollowKnight/icons/misc/Grub.png',
  home: '/assets/icon.png',
  ismasTear: '/assets/hollowKnight/icons/skills/IsmasTear.png',
  loveKey: '/assets/hollowKnight/icons/items/LoveKey.png',
  maskShard0: '/assets/hollowKnight/icons/fragments/MaskShard0.png',
  maskShard1: '/assets/hollowKnight/icons/fragments/MaskShard1.png',
  maskShard2: '/assets/hollowKnight/icons/fragments/MaskShard2.png',
  maskShard3: '/assets/hollowKnight/icons/fragments/MaskShard3.png',
  simpleKey: '/assets/hollowKnight/icons/items/SimpleKey.png',
  slyKey: '/assets/hollowKnight/icons/items/SlyKey.png',
  stag: '/assets/hollowKnight/icons/misc/Stag.png',
  vesselFrag0: '/assets/hollowKnight/icons/fragments/VesselFrag0.png',
  vesselFrag1: '/assets/hollowKnight/icons/fragments/VesselFrag1.png',
  vesselFrag2: '/assets/hollowKnight/icons/fragments/VesselFrag2.png',
  whisperingRoots: '/assets/hollowKnight/icons/misc/WhisperingRoot.png',
  whitheFrgamentLeft: '/assets/hollowKnight/icons/charms/WhiteFragmentLeft.png',
}

export const LOGOS = {
  home: '/assets/hollowKnight/logos/home.png',
}
